// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_47KjwC2mcvht8Ik6dBblW8WUqVQ3reE',
    appId: '1:273962086975:web:ec7daef5bdac9d2cb43e8a',
    messagingSenderId: '273962086975',
    projectId: 'fluttertest-91869',
    authDomain: 'fluttertest-91869.firebaseapp.com',
    storageBucket: 'fluttertest-91869.appspot.com',
    measurementId: 'G-9FVXZJ8YRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIyw4OFDha2WAEoK4smJ46xwnegiynHAw',
    appId: '1:273962086975:android:621788738d4d778fb43e8a',
    messagingSenderId: '273962086975',
    projectId: 'fluttertest-91869',
    storageBucket: 'fluttertest-91869.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFnwGYdItopPg218kAzYIKriEy2N_n4Po',
    appId: '1:273962086975:ios:04213e8c92066122b43e8a',
    messagingSenderId: '273962086975',
    projectId: 'fluttertest-91869',
    storageBucket: 'fluttertest-91869.appspot.com',
    iosBundleId: 'com.example.beyana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFnwGYdItopPg218kAzYIKriEy2N_n4Po',
    appId: '1:273962086975:ios:04213e8c92066122b43e8a',
    messagingSenderId: '273962086975',
    projectId: 'fluttertest-91869',
    storageBucket: 'fluttertest-91869.appspot.com',
    iosBundleId: 'com.example.beyana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_47KjwC2mcvht8Ik6dBblW8WUqVQ3reE',
    appId: '1:273962086975:web:701ca6d53533c416b43e8a',
    messagingSenderId: '273962086975',
    projectId: 'fluttertest-91869',
    authDomain: 'fluttertest-91869.firebaseapp.com',
    storageBucket: 'fluttertest-91869.appspot.com',
    measurementId: 'G-7NW0B3YXZE',
  );
}
